import {calculateMme} from '../lib/mme';
import {summary} from '../lib/tlfb';
import {reasonLabel} from '../lib/workspace';
import {usesHeal} from '../lib/mme-reference';
import type {ResearchSession} from '../lib/research-session';
import {MedicationSummary} from './medication-summary';
import * as exports from '../lib/research-exports';

export const show = (n: number | null) => n === null ? '—' : n.toLocaleString('en-US', {maximumFractionDigits: 2});
export function ResearchSummary({session, result, onExport, onBundle, onPrint, busy}: {session: ResearchSession; result: ReturnType<typeof calculateMme>; onExport: (label: string, data: string) => void; onBundle?: () => void; onPrint: () => void; busy: boolean}) {
  const w = result.window;
  const reviews = result.medicationRows.filter(r => r.status === 'needs_review');
  return <section className="panel summary"><p className="eyebrow">03 / RESEARCH SUMMARY</p><h2>MME results</h2>
    <p>Conversion table: <strong>{session.reference.title}</strong>. {usesHeal(session.reference) ? 'Buprenorphine for pain is included; OUD buprenorphine and excluded medications/routes are reported separately.' : 'Included opioids only. Buprenorphine and excluded medications/routes are reported separately.'} {w.status === 'not_applicable' ? 'MME is not applicable: no included opioid is configured.' : `${w.calculableDays} of ${w.daysInScope} recall days are fully calculable.`}</p>
    {session.medications.some(m => m.genericName === 'methadone' && m.route === 'oral') && <p>Oral methadone recorded for pain or OUD contributes to these research totals at 4.7 × mg/day. This research convention must not be used for OUD dosing decisions.</p>}
    <div className="mme-grid">
      <div><span>Total MME</span><strong data-testid="total-mme">{show(w.totalMme)}</strong><small>{w.status === 'complete' ? 'Entire recall window' : 'Unavailable until the window is complete'}</small></div>
      <div><span>Average · all recall days</span><strong data-testid="average-all">{show(w.averageAllDays)}</strong><small>MME/day · {w.daysInScope} recall days; confirmed zeros included</small></div>
      <div><span>Average · answered days</span><strong data-testid="average-answered">{show(w.averageAnsweredDays)}</strong><small>MME/day · {w.calculableDays} fully calculable days</small></div>
      <div><span>Maximum daily MME</span><strong data-testid="maximum-mme">{show(w.maximumDailyMme)}</strong><small>{w.status === 'complete' ? 'Entire recall window' : `Observed on calculable days: ${show(w.observedMaximumDailyMme)}`}</small></div>
    </div>
    {w.status === 'incomplete' && <p className="alert">{w.unansweredMedicationEntries} unanswered opioid entries; {w.reviewMedicationEntries} entries need review. Sum of complete days: {show(w.completeDayTotal)} MME. Recorded component subtotal: {show(w.recordedComponentSubtotal)} MME (may include partial days; not the window total).</p>}
    <p>“Answered days” here means days with a calculable response for every included opioid. A use response with unknown quantity or strength is recorded but cannot enter that average. Missing days are never zero.</p>
    {session.medications.length > 0 && <details className="summary-heading"><summary>By medication</summary><MedicationSummary session={session} result={result}/></details>}
    <details className="summary-heading"><summary>Calendar-month results</summary><p>Each month includes only dates inside this recall window. A partial calendar month is not extrapolated to 30 days.</p>
    <div className="table-scroll"><table><thead><tr><th>Month / dates</th><th>Status</th><th>Calculable / recall days</th><th>Total MME</th><th>Average all days</th><th>Average answered</th><th>Full / observed max</th></tr></thead><tbody>{result.months.map(m => <tr key={m.period}><th>{m.period}<small>{m.start} – {m.end}</small></th><td>{m.status.replace('_', ' ')}</td><td>{m.calculableDays} / {m.daysInScope}</td><td>{show(m.totalMme)}</td><td>{show(m.averageAllDays)}</td><td>{show(m.averageAnsweredDays)}</td><td>{show(m.maximumDailyMme)} / {show(m.observedMaximumDailyMme)}</td></tr>)}</tbody></table></div>
    </details>
    {reviews.length > 0 && <details className="summary-heading"><summary>{reviews.length} medication entries need review</summary><div className="table-scroll"><table><thead><tr><th>Date</th><th>Medication</th><th>Reason</th></tr></thead><tbody>{reviews.map(r => <tr key={r.date + r.medicationId}><td>{r.date}</td><th>{session.medications.find(m => m.id === r.medicationId)?.name}</th><td>{reasonLabel(r.reason)}</td></tr>)}</tbody></table></div></details>}
    {result.excluded.length > 0 && <><h3 className="summary-heading">Excluded from MME</h3><ul>{result.excluded.map(m => <li key={m.medicationId}>{m.name}: {reasonLabel(m.reason)}</li>)}</ul></>}
    {result.buprenorphine.length > 0 && <><h3 className="summary-heading">{result.buprenorphine.some(b => b.separateMmeFactor !== null) ? 'Buprenorphine · kept out of MME totals' : 'Buprenorphine · separate quantities, no MME conversion'}</h3><p>Totals below cover reported quantities only; check missing and unknown-quantity days. Different medications and strengths remain separate. Injection days count administrations, not days of medication effect; pump doses count the amount delivered on recorded dates.</p><div className="table-scroll"><table><thead><tr><th>Medication</th><th>Use / administration days</th><th>No use / no administration</th><th>Unanswered</th><th>Unknown quantity / dose</th><th>Reported quantity</th><th>Mean quantity / answered day</th><th>Reported dose (mg)</th>{result.buprenorphine.some(b => b.separateMmeFactor !== null) && <th>Separate MME (NIH HEAL)</th>}</tr></thead><tbody>{result.buprenorphine.map(b => <tr key={b.medicationId}><th>{b.name}<small>{b.route}</small></th><td>{b.useDays}</td><td>{b.noUseDays}</td><td>{b.missingDays}</td><td>{b.unknownQuantityDays} / {b.unknownDoseDays}</td><td>{show(b.totalReportedQuantity)} {b.quantityUnit}</td><td>{show(b.meanQuantityPerAnsweredDay)}</td><td>{show(b.totalReportedDoseMg)}</td>{result.buprenorphine.some(x => x.separateMmeFactor !== null) && <td data-testid="bup-separate-mme">{b.separateMmeFactor === null ? 'No factor' : <>{show(b.separateMmeFullWindow ?? b.separateMmeRecordedSubtotal)}<small>{b.separateMmeFullWindow === null ? 'Recorded so far; not a full total' : 'Full recall window'}</small></>}</td>}</tr>)}</tbody></table></div></>}
    {session.substances.length > 0 && <><h3 className="summary-heading">Other substance summaries</h3><div className="table-scroll"><table><thead><tr><th>Substance / unit</th><th>Answered</th><th>Missing</th><th>No use</th><th>Use days</th><th>Reported total</th><th>Mean / answered day</th></tr></thead><tbody>{session.substances.map(s => {const q = summary({...session, version: 1}, s); return <tr key={s.id}><th>{s.name}<small>{s.unit}</small></th><td>{q.answered}</td><td>{q.missing}</td><td>{q.zeroDays}</td><td>{q.useDays}</td><td>{show(s.kind === 'quantity' && q.answered ? q.total : null)}</td><td>{show(q.mean)}</td></tr>;})}</tbody></table></div></>}
    <div className="export-notes"><div><h3>Research exports</h3><p>Session files reopen the interview. CSVs are analysis outputs, with unanswered values left blank and status fields included.</p><fieldset className="plain-fieldset" disabled={busy}><div className="inline-actions">{onBundle && <button className="primary" onClick={onBundle}>Save export folder</button>}<button onClick={onPrint}>Print summary</button></div><details className="summary-heading"><summary>Individual CSV files</summary><div className="inline-actions">
      <button className="primary" onClick={() => onExport('combined-daily', exports.combinedDailyCsv(session))}>Combined daily CSV</button>
      <button className="primary" onClick={() => onExport('combined-summary', exports.combinedSummaryCsv(session))}>Combined summary CSV</button>
      <button onClick={() => onExport('substance-daily', exports.researchSubstanceCsv(session))}>Substance daily CSV</button>
      <button onClick={() => onExport('substance-summary', exports.researchSubstanceSummaryCsv(session))}>Substance summary CSV</button>
      <button onClick={() => onExport('medication-daily', exports.medicationCsv(session))}>Medication daily CSV</button>
      <button onClick={() => onExport('mme-daily', exports.dailyMmeCsv(session))}>MME daily CSV</button>
      <button onClick={() => onExport('mme-summary', exports.mmeSummaryCsv(session))}>MME summary CSV</button>
      {result.buprenorphine.length > 0 && <button onClick={() => onExport('buprenorphine', exports.buprenorphineCsv(session))}>Buprenorphine CSV</button>}
    </div></details></fieldset><p>Save export folder keeps a session file and both combined CSVs together in a new folder. Individual CSV files are also available above.</p><details><summary>About these exports</summary><p>Combined daily CSV: one row per date with MME, medication details, other substances and notes. Combined summary CSV: one interview row with MME totals/averages, calendar-month MME and substance-use days. Buprenorphine stays separate from MME.</p></details></div><div><details><summary>Calculation reference</summary><p>{session.reference.title}. Reference: {session.reference.id}. Policy: {session.reference.policyId}. Full-precision values and reference identifiers are included in exports. Screen values are rounded to two decimal places.</p><p>Source (for independent review): {session.reference.sourceUrl}</p></details></div></div>
  </section>;
}
