export type Substance = {id:string; name:string; unit:string; kind:'quantity'|'binary'};
export type Interview = {version:1; participantId:string; assessor:string; assessmentDate:string; recallDays:number; substances:Substance[]; responses:Record<string,number>; notes:Record<string,string>};
export function validDate(value:string):boolean {return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;}
export function shiftDate(value:string,days:number):string {if(!validDate(value))throw new Error('Enter a valid assessment date.');const date=new Date(value+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
export function datesFor(date:string,days:number):string[]{if(!Number.isInteger(days)||days<1||days>90)throw new Error('Recall window must be 1–90 days.');return Array.from({length:days},(_,i)=>shiftDate(date,i-days));}
export const keyFor=(date:string,id:string)=>`${date}|${id}`;
export function validateSetup(i:Interview):void{datesFor(i.assessmentDate,i.recallDays);if(!i.participantId.trim())throw new Error('Enter a participant code.');if(i.substances.length<1||i.substances.length>12)throw new Error('Choose 1–12 substances.');const names=new Set<string>(),ids=new Set<string>();for(const s of i.substances){if(!s.name.trim()||!s.unit.trim())throw new Error('Every substance needs a name and unit.');if(!/^[a-zA-Z0-9_-]+$/.test(s.id)||ids.has(s.id))throw new Error('Substance IDs must be unique.');if(names.has(s.name.trim().toLowerCase()))throw new Error('Substance names must be unique.');if(!['binary','quantity'].includes(s.kind))throw new Error('Unknown measurement type.');names.add(s.name.trim().toLowerCase());ids.add(s.id);}}
export function parseAmount(value:string,kind:Substance['kind']):number {if(value.trim()==='')throw new Error('Enter a value, or use Clear response.');const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('Use a finite number of zero or greater.');if(kind==='binary'&&n!==0&&n!==1)throw new Error('Use-only responses must be 0 (no use) or 1 (use).');return n;}
export function summary(i:Interview,s:Substance){const dates=datesFor(i.assessmentDate,i.recallDays);const values=dates.map(d=>i.responses[keyFor(d,s.id)]).filter(v=>v!==undefined);const answered=values.length;const useDays=values.filter(v=>v>0).length;const total=values.reduce((a,b)=>a+b,0);return {answered,missing:dates.length-answered,zeroDays:answered-useDays,useDays,total,percentUse:answered?100*useDays/answered:null,mean:s.kind==='quantity'&&answered?total/answered:null};}
export function dayState(i:Interview,date:string){if(!datesFor(i.assessmentDate,i.recallDays).includes(date))return 'outside';const vs=i.substances.map(s=>i.responses[keyFor(date,s.id)]);if(vs.every(v=>v===undefined))return 'unanswered';if(vs.some(v=>v===undefined))return 'partial';return vs.some(v=>v!>0)?'use':'zero';}
function csvCell(value:unknown):string {let s=value===null||value===undefined?'':String(value);if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function csv(rows:unknown[][]):string{return '\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')+'\r\n';}
export function dailyCsv(i:Interview):string {validateSetup(i);return csv([['participant_id','assessor','assessment_date','recall_start','recall_end','date','substance_id','substance','measurement','unit','status','value','event_note'],...datesFor(i.assessmentDate,i.recallDays).flatMap(d=>i.substances.map(s=>{const v=i.responses[keyFor(d,s.id)];return [i.participantId,i.assessor,i.assessmentDate,shiftDate(i.assessmentDate,-i.recallDays),shiftDate(i.assessmentDate,-1),d,s.id,s.name,s.kind,s.unit,v===undefined?'unanswered':v===0?'no_use':'use',v,i.notes[d]??''];}))]);}
export function summaryCsv(i:Interview):string{validateSetup(i);return csv([['participant_id','assessment_date','recall_days','substance_id','substance','unit','measurement','answered_days','missing_days','no_use_days','use_days','percent_use_of_answered_days','total_on_answered_days','mean_per_answered_day'],...i.substances.map(s=>{const q=summary(i,s);return [i.participantId,i.assessmentDate,i.recallDays,s.id,s.name,s.unit,s.kind,q.answered,q.missing,q.zeroDays,q.useDays,q.percentUse,s.kind==='quantity'&&q.answered?q.total:null,q.mean];})]);}
export function parseInterview(text:string):Interview {const i=JSON.parse(text);if(!i||i.version!==1||typeof i.participantId!=='string'||typeof i.assessor!=='string'||typeof i.assessmentDate!=='string'||!Array.isArray(i.substances)||!i.substances.every((s:Substance)=>s&&typeof s.id==='string'&&typeof s.name==='string'&&typeof s.unit==='string')||!i.responses||Array.isArray(i.responses)||typeof i.responses!=='object'||!i.notes||Array.isArray(i.notes)||typeof i.notes!=='object')throw new Error('This is not a valid TLFB Calendar session.');validateSetup(i);const ds=datesFor(i.assessmentDate,i.recallDays);const allowed=new Map(ds.flatMap(d=>i.substances.map((s:Substance)=>[keyFor(d,s.id),s] as const)));for(const [key,value] of Object.entries(i.responses)){const s=allowed.get(key) as Substance|undefined;if(!s||typeof value!=='number')throw new Error('Session contains an invalid response.');parseAmount(String(value),s.kind);}for(const [date,note] of Object.entries(i.notes))if(!ds.includes(date)||typeof note!=='string'||note.length>2000)throw new Error('Session contains an invalid note.');return i;}
export function newInterview():Interview{return {version:1,participantId:'',assessor:'',assessmentDate:'2026-09-27',recallDays:30,substances:[{id:'alcohol',name:'Alcohol',unit:'standard drinks',kind:'quantity'},{id:'nicotine',name:'Nicotine',unit:'cigarettes',kind:'quantity'},{id:'cannabis',name:'Cannabis',unit:'use / no use',kind:'binary'}],responses:{},notes:{}};}
export function demoInterview():Interview {const i=newInterview();i.participantId='DEMO-001';i.assessor='Demo interviewer';datesFor(i.assessmentDate,i.recallDays).forEach((d,n)=>{if(n>25)return;i.substances.forEach((s,k)=>{if(n===24&&k===2)return;i.responses[keyFor(d,s.id)]=k===0?(n%7===3?2:0):k===1?4+n%3:(n%6===0?1:0);});});i.notes['2026-09-05']='Family birthday dinner';i.notes['2026-09-14']='First day of a new work schedule';return i;}
